#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Oct 28 04:16:36 +08 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim axi_fifo2_behav -key {Behavioral:sim_1:Functional:axi_fifo2} -tclbatch axi_fifo2.tcl -protoinst "protoinst_files/bram_1.protoinst" -log simulate.log"
xsim axi_fifo2_behav -key {Behavioral:sim_1:Functional:axi_fifo2} -tclbatch axi_fifo2.tcl -protoinst "protoinst_files/bram_1.protoinst" -log simulate.log

